# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answeredQuestions',
            field=models.ManyToManyField(to='election.Question'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('band', 'Band'), ('athletics', 'Athletics'), ('debate', 'Debate'), ('art', 'Art')], max_length=10),
        ),
    ]
