# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20160201_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='spec',
            field=models.CharField(choices=[('band', 'Band'), ('athletics', 'Athletics'), ('debate', 'Debate'), ('art', 'Art'), ('any', 'any')], default='any', max_length=25),
        ),
    ]
