# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='winner',
            field=models.CharField(default='', max_length=300),
        ),
    ]
